import { Books } from '@/entities';

export const booksData: Books[] = [
  // 2020
  { _id: crypto.randomUUID(), title: 'Come trattare gli altri e farseli amici', author: 'Dale Carnegie', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'Sapiens da animali a dei', author: 'Yuval Noah Harari', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'Niente teste di cazzo', author: 'James Kerr', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'Guida pratica alla psicopatologia della vita quotidiana', author: 'Costanza Jesurum', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'Perché ?', author: 'Umberto Galimberti', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'Fattore 1%', author: 'Luca Mazzucchelli', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'Il segreto dei Giganti', author: 'Timothy Ferris', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'Jugaad innovation', author: 'Navi Radjou e Simone Ahuj', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'Innovatori', author: 'Massimo Temporelli', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'The Four i padroni', author: 'Scott Galloway', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'È molto semplice', author: 'Massimiliano Allegri', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'Lavorability', author: 'Marco Montemagno', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'Le 21 leggi fondamentali del leader', author: 'John c. Maxwell', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'Sono un ottimista globale', author: 'Massimo Franco', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'l\'era del cuore', author: 'Luca Mazzucchelli', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'Perché alle zebre non viene l\'ulcera', author: '', yearRead: 2020 },
  { _id: crypto.randomUUID(), title: 'the Almanack of Naval Ravikant', author: 'Eric Jorgenson', yearRead: 2020 },

  // 2021
  { _id: crypto.randomUUID(), title: 'il metodo danese per crescere bambini felici ed essere genitori sereni', author: 'Iben Sandahl e Jessica Alexander', yearRead: 2021 },
  { _id: crypto.randomUUID(), title: 'Nella testa del dragone', author: 'FEDERICO Rampini', yearRead: 2021 },
  { _id: crypto.randomUUID(), title: 'Inventa e sogna', author: 'Jeff Besos', yearRead: 2021 },
  { _id: crypto.randomUUID(), title: 'Tim Cook - il genio che ha cambiato Apple', author: '', yearRead: 2021 },
  { _id: crypto.randomUUID(), title: 'errore di sistema', author: 'Edward snowden', yearRead: 2021 },
  { _id: crypto.randomUUID(), title: 'jack ma autobiografia', author: '', yearRead: 2021 },
  { _id: crypto.randomUUID(), title: 'l\'autore di giochi', author: 'Emiliano Sciarra', yearRead: 2021 },
  { _id: crypto.randomUUID(), title: 'Greenlights', author: 'Matthew McConaughey', yearRead: 2021 },
  { _id: crypto.randomUUID(), title: 'fermare Pechino', author: 'Federico Rampini', yearRead: 2021 },
  { _id: crypto.randomUUID(), title: 'forte come l\'acqua', author: 'Filippo Ongaro', yearRead: 2021 },
  { _id: crypto.randomUUID(), title: 'cervello superveloce', author: 'Riccardo Ceccarelli', yearRead: 2021 },
  { _id: crypto.randomUUID(), title: 'dovremmo essere tutti femministi', author: 'Chimamanda Ngozi Adichie', yearRead: 2021 },
  { _id: crypto.randomUUID(), title: 'homo deus', author: 'Harari', yearRead: 2021 },
  { _id: crypto.randomUUID(), title: 'factfulness', author: 'hans Rosling', yearRead: 2021 },

  // 2022
  { _id: crypto.randomUUID(), title: 'Consigli da un amico', author: 'Tony Robbins', yearRead: 2022 },
  { _id: crypto.randomUUID(), title: 'Parlare in pubblico', author: 'Romana Garassini', yearRead: 2022 },
  { _id: crypto.randomUUID(), title: 'Rich Devos - lezioni di vita', author: '', yearRead: 2022 },
  { _id: crypto.randomUUID(), title: 'Trova il tuo perché', author: 'Simon Sinek', yearRead: 2022 },
  { _id: crypto.randomUUID(), title: 'La vita non è un film', author: 'Pino Insegno', yearRead: 2022 },
  { _id: crypto.randomUUID(), title: 'Investire come il più grande hedge fund Al mondo', author: 'Gabriele Galletta', yearRead: 2022 },
  { _id: crypto.randomUUID(), title: 'Essere leader', author: 'Daniel goldman', yearRead: 2022 },
  { _id: crypto.randomUUID(), title: 'il cigno nero', author: 'Nassim Nicholas Taleb', yearRead: 2022 },
  { _id: crypto.randomUUID(), title: 'La mucca viola', author: 'Seth Godin', yearRead: 2022 },
  { _id: crypto.randomUUID(), title: 'suicidio occidentale', author: 'FEDERICO Rampini', yearRead: 2022 },
  { _id: crypto.randomUUID(), title: 'riscrivi le pagine della tua vita', author: 'Anna De Simone', yearRead: 2022 },

  // 2023
  { _id: crypto.randomUUID(), title: 'oltre il possibile', author: 'Nimsdai Purja', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'leadership e gestione delle risorse umane', author: 'Emanuele Romano', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'How to built a car', author: 'Adrian Newey', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'il metodo geniale', author: 'Giuliano Deangeli', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'la mappa delle culture', author: 'Erin Meyer', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'Emotional Mapping', author: 'Luigi Poto', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'd\'amore ci si ammala, d\'amore si guarisce', author: 'Anna De Simone', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'le parole di Gesù', author: 'Umberto Galimberti', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'domande brillanti', author: 'Warren Berger', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'le 7 regole per avere successo', author: 'Stephen Covey', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'ragionare meglio per vivere meglio', author: 'woo-kyoung ahn', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'La mente ferita', author: 'Giorgio Nardone', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'l\'Ingannevole paura di non essere all\'altezza', author: 'Roberta Milanese', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'il potere di adesso', author: 'Eckhart Tolle', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'una terra promessa', author: 'Barack Obama', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'Awareness', author: 'Osho', yearRead: 2023 },
  { _id: crypto.randomUUID(), title: 'the Mamba Mentality', author: '', yearRead: 2023 },

  // 2024
  { _id: crypto.randomUUID(), title: 'India Darshan', author: 'Samsara roads Instagram', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Il cambiamento strategico', author: 'Giorgio Nardone', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Stanco di essere stanco ?', author: 'Nicola Triglione', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'I 5 linguaggi dell\'amore', author: 'Gary Chapman', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'The Power of fun', author: 'Catherine Price', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Il colloquio strategico in azienda', author: 'Giorgio Nardone', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Coaching strategico', author: 'Roberta Milanese, Giorgio Nardone', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Pensaci ancora', author: 'Adam Grant', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Se solo sapeste', author: 'David Garrett', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Profondo come il mare, leggero come il cielo', author: 'Gianluca Gotto', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Kintsugi, L\'arte di ricostruire la fiducia', author: 'Gregorio Di Leo', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Il leader calmo', author: 'Carlo Ancelotti', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Noi inarrestabili, perché il mondo è ingiusto', author: 'Yuval Noah Harari', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Il libro delle Emozioni', author: 'Umberto Galimberti', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Troppo comodi', author: 'Michael Easter', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Il gioco interiore nel tennis', author: 'Timothy Gallery', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Ikigai. Il metodo giapponese', author: 'Bettina Lemke', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Rabbia', author: 'Roberta Milanese', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Piovono Talenti', author: 'Samantha Marzullo', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'La seconda onda', author: 'Arthur Brooks', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Quando inizia la felicità', author: 'Gianluca Gotto', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Nelle tempeste del futuro', author: 'Pietro Trabucchi', yearRead: 2024 },
  { _id: crypto.randomUUID(), title: 'Opus: manuale di automotivazione', author: 'Pietro Trabucchi', yearRead: 2024 },

  // 2025
  { _id: crypto.randomUUID(), title: 'Un uomo in cerca di senso, Uno psicologo nei Lager', author: 'Vicktor Frankl', yearRead: 2025 },
  { _id: crypto.randomUUID(), title: 'Sfacciati', author: 'Mick Odelli', yearRead: 2025 },
  { _id: crypto.randomUUID(), title: 'intelligenza artificiale', author: 'Francesca Rossi', yearRead: 2025 },
  { _id: crypto.randomUUID(), title: 'Nella mente del campione', author: 'Riccardo Ceccarelli', yearRead: 2025 },
  { _id: crypto.randomUUID(), title: 'La rivincita dei punti deboli', author: 'Roberta Milanese', yearRead: 2025 },
  { _id: crypto.randomUUID(), title: 'Nvidia e il genio di Jensen Huang', author: 'Tar Kim', yearRead: 2025 },
  { _id: crypto.randomUUID(), title: 'il computer impossibile', author: '', yearRead: 2025 },
  { _id: crypto.randomUUID(), title: 'Il dilemma dell\'innovatore', author: 'Clayton Christensen', yearRead: 2025 },
  { _id: crypto.randomUUID(), title: '101 riflessioni che cambiano il tuo modo di pensare', author: 'Brianna Wiest', yearRead: 2025 },
  { _id: crypto.randomUUID(), title: 'Nudge. La spinta gentile', author: '', yearRead: 2025 },
  { _id: crypto.randomUUID(), title: 'il tao della fisica', author: '', yearRead: 2025 },
  { _id: crypto.randomUUID(), title: 'Piccolo almanacco dell\'attore', author: 'Fabrizio bentivoglio', yearRead: 2025 },
  { _id: crypto.randomUUID(), title: 'la lezione del Giappone', author: 'Federico Rampini', yearRead: 2025 },
  { _id: crypto.randomUUID(), title: 'I 4 pilastri dell\'indipendenza finanziaria', author: 'Marco Casario', yearRead: 2025 },
];
